services:
  dbt:
    build:
      context: .
    volumes:
      - ./requirements.txt:/usr/app/requirements.txt
      - ./dbt_project.yml:/usr/app/dbt_project.yml
      - ./models:/usr/app/models
      - ./.sqlfluff:/usr/app/.sqlfluff
      - ./.sqlfluffignore:/usr/app/.sqlfluffignore
    secrets:
      - dbt_profiles_yml
      - snowflake_private_key

secrets:
  dbt_profiles_yml:
    environment: DBT_PROFILES_YML
  snowflake_private_key:
    environment: SNOWFLAKE_PRIVATE_KEY
