services:
  dbt:
    build:
      context: .
    volumes:
      - ./requirements.txt:/usr/app/requirements.txt
      - ./models:/usr/app/models
    secrets:
      - dbt_profiles_yml
      - snowflake_private_key

secrets:
  dbt_profiles_yml:
    environment: DBT_PROFILES_YML
  snowflake_private_key:
    environment: SNOWFLAKE_PRIVATE_KEY
