services:
  dbt:
    build:
      context: .
    secrets:
      - dbt_profiles_yml
      - snowflake_private_key

secrets:
  dbt_profiles_yml:
    environment: DBT_PROFILES_YML
  snowflake_private_key:
    environment: SNOWFLAKE_PRIVATE_KEY
