services:
  dbt:
    build:
      context: .
    secrets:
      - source: dbt_profiles_yml
        target: /run/secrets/dbt_profiles.yml
      - snowflake_private_key

secrets:
  dbt_profiles_yml:
    file: ${DBT_PROFILES_YML}
  snowflake_private_key:
    file: ${SNOWFLAKE_PRIVATE_KEY}
